### ISSUE TITLE
Why Rabin was implemented as a Duplex instead of a Transform?

### ISSUE THREAD

**Issue by green-coder** [maxogden/rabin#5]
It is not an issue, it is just a question.

**Comment by mafintosh** [comment]
high level wise it is still a transform stream. the problem with doing this a pure transform stream is that transform streams currently do not have a [writev api](https://nodejs.org/api/stream.html#stream_writable_writev_chunks_callback) that is called with all the pending buffers waiting to be transformed. this is important because we wanna minimise context shifting between node and c to get decent performance.

**Comment by mafintosh** [comment]
@green-coder if you're on IRC you should join #dat on freenode btw :)
